### ISSUE TITLE
Multiple Glider.js Instances

### ISSUE THREAD

**Issue by beanyhodge** [NickPiscitelli/Glider.js#24]
@NickPiscitelli, loving the slider so far. The first issue I've run into is around hosting multiple glider instances within the same page. Only the first instance appears to work.

Do I need to declare multiple event listeners during the build phase or is there some other magic I'm missing.

This must be possible because you have multiple demo instances on your site: https://nickpiscitelli.github.io/Glider.js/

(stumbled upon your code watching DesignCourse's YouTube video: https://www.youtube.com/watch?v=FT9e8EQi8ys)

**Comment by NickPiscitelli** [comment]
What does your initialization code look like? You need to initialize the
Glider object for each element that you want it to run on. You can't pass a
list of elements to Glider and have it initialize all of them.

Example:
[].forEach.call(document.querySelectorAll('.glider'), function(ele){
    new Glider(ele, options);
});

**Comment by NickPiscitelli** [comment]
The problem is that `document.querySelector('.glider')` only ever gets one
element. It looks like you are looking for something more like:

window.addEventListener('load', function () {
[].forEach.call(document.querySelectorAll('.glider'), function(ele){
ele.addEventListener('glider-slide-visible', function (event) { var glider
= Glider(this); console.log('Slide Visible %s', event.detail.slide) });
ele.addEventListener('glider-slide-hidden', function (event) {
console.log('Slide Hidden %s', event.detail.slide) });
ele.addEventListener('glider-refresh', function (event) {
console.log('Refresh') }); ele.addEventListener('glider-loaded', function
(event) { console.log('Loaded') }); new Glider(ele, { slidesToShow: 1,
slidesToScroll: 1, scrollLock: true, draggable: true, dots: '#dots',
arrows: { prev: '.glider-prev', next: '.glider-next' } }); }); });

**Comment by NickPiscitelli** [comment]
Yeah, that makes sense, you'll need to be more specific in your arrow
arguments. Replace the Glider initialization call with this:

new Glider(ele, { slidesToShow: 1, slidesToScroll: 1, scrollLock: true,
draggable: true, dots: ele.querySelector('#dots'), arrows: { prev:
ele.querySelector('.glider-prev'), next: ele.querySelector('.glider-next')
} });
Also, you have `dots` set with an ID right now, you'll need to switch it to
a class since duplicated IDs are invalid.

**Comment by beanyhodge** [comment]
Ok, so heres the updated `<script>`

          window.addEventListener('load', function () {
                [].forEach.call(document.querySelectorAll('.glider'), function (ele) {
                    ele.addEventListener('glider-slide-visible', function (event) {
                        var glider
                            = Glider(this); console.log('Slide Visible %s', event.detail.slide)
                    });
                    ele.addEventListener('glider-slide-hidden', function (event) {
                        console.log('Slide Hidden %s', event.detail.slide)
                    });
                    ele.addEventListener('glider-refresh', function (event) {
                        console.log('Refresh')
                    });
                    ele.addEventListener('glider-loaded', function
                        (event) {
                            console.log('Loaded')
                    });
                    new Glider(ele, {
                        slidesToShow: 1,
                        slidesToScroll: 1,
                        scrollLock: true,
                        draggable: true,
                        dots: ele.querySelector('.dots'),
                        arrows: {
                            prev: ele.querySelector('.glider-prev'),
                            next: ele.querySelector('.glider-next')
                        }
                    });
                });
            });

With two `<div>` gliders:

        <div class="glider-contain multiple">
            <div class="glider">
                <div><img alt="Test" src="http://placehold.it/300x300?text=1"></div>
                <div><img alt="Test" src="http://placehold.it/300x300?text=2"></div>
                <div><img alt="Test" src="http://placehold.it/300x300?text=3"></div>
            </div>
            <button class="glider-prev">&laquo;</button>
            <button class="glider-next">&raquo;</button>
            <div class="dots"></div>
        </div>
        
        <div class="glider-contain multiple">
            <div class="glider">
                <div><img alt="Test" src="http://placehold.it/300x300?text=1"></div>
                <div><img alt="Test" src="http://placehold.it/300x300?text=2"></div>
                <div><img alt="Test" src="http://placehold.it/300x300?text=3"></div>
            </div>
            <button class="glider-prev">&laquo;</button>
            <button class="glider-next">&raquo;</button>
            <div class="dots"></div>
        </div>

Click and drag functionality works for both.
`'.glider-prev'` and `'.glider-next'` _appear_ for both but don't work for either.
Dots don't appear at all.

**Comment by NickPiscitelli** [comment]
Since the dots/arrows live outside of the glider element, the
initialization call needs to be:

new Glider(ele, {
                    slidesToShow: 1,
                    slidesToScroll: 1,
                    scrollLock: true,
                    draggable: true,
                    dots: ele.parentNode.querySelector('.dots'),
                    arrows: {
                        prev: ele.parentNode.querySelector('.glider-prev'),
                        next: ele.parentNode.querySelector('.glider-next')
                    }
                });


I'll probably update the docs to be more explicit in this regard.

**Comment by beanyhodge** [comment]
All working thank you! Really appreciate your help.

**Comment by NickPiscitelli** [comment]
No problem, things can be a little tricky without jQuery, really made a lot
of things much easier.

**Comment by danielrussellLA** [comment]
for those using `react-glider`, i found a way to fix having multiple gliders per page:

```
<div className="carousel-container">
     <div id="arrow-left"><</div>
        <Glider
            hasArrows
            arrows={{
                prev: "#arrow-left",
                next: "#arrow-right",
            }}
        />
     <div id="arrow-right">></div>
</div>
```
