### ISSUE TITLE
Flash of content

### ISSUE THREAD

**Issue by tarponjargon** [NickPiscitelli/Glider.js#75]
Really like glider - thanks for making it.  I'm having a problem where when the slides load they briefly flash in the container.  See this video:

[https://youtu.be/n-OfvAkgafE](https://youtu.be/n-OfvAkgafE)

I am loading the first image in the server-side-rendered html then updating the div when glider inits (that's when the flash occurs).

Is there any way to combat that?  I've tried to CSS my way out of it but haven't quite figured out a way.  Has anyone faced this issue before?

**Comment by NickPiscitelli** [comment]
You will want to hide the container div until right before glider is initialized. Depending upon how this is achieved, you might have a race condition where Glider can't properly calculate heights due to hidden elements, but you can always work around this by using visibility over display to hide. 

Additionally, you could always use the loaded event to display the images instead.

**Comment by tarponjargon** [comment]
Thanks for responding, Nick.  I played around with it some more and this seems to work.

in css:

```
.gallery-item img:nth-child(n + 2) {
	visibility: hidden;
}
```

in the js:

```
let self = this;
this.galleryEl.addEventListener("glider-loaded", function() {
	self.galleryEl.querySelectorAll(".gallery-item img").forEach(i => {
		i.style.visibility = "visible";
	});
});
```

Tried to avoid using the nth selector...like trying to toggle the visibility on .gallery-item, .glider or .glider-track...but those didn't seem to work.  nth is fine though.
