### ISSUE TITLE
Fractional slides cannot be itemWidth-based

### ISSUE THREAD

**Issue by constb** [NickPiscitelli/Glider.js#9]
Hi. I'm making a responsive website and I want to display fixed-width slides in a responsive carousel.

Unfortunately, fractional slides only work with fractional `slidesToShow`, which in my case in not a fixed number. When I set `slidesToShow: "auto"` and a fixed `itemWidth`, Glider makes slides wider to fit a non-fractional number of items on a screen.

In the following lines:

```
    if (_.opt.slidesToShow === 'auto'){
      _.opt.slidesToShow = Math.floor(_.containerWidth / _.opt.itemWidth);
    }
```

…the use of `Math.floor` is responsible for this (in my case unwanted) behaviour.

I managed to override the displayed item width using `max-width` in CSS, but the "scroll lock" function is now broken, since it's using this wrong, internally calculated width, instead of the one from settings.

So my proposal is this: when `itemWidth` is set by the user, assume that user wants fractional slides. Also when `itemWidth` is set, use it instead of a calculated one in scroll lock.

Or alternatively even read actual widths from the DOM – this may allow later to implement a slider with items with different widths. In this case setting `slidesToShow: "auto"` without specifying `itemWidth` may indicate that slides' widths must be read from the DOM. Scroll lock will probably become more complex, since breakpoints won't be uniform anymore…

**Comment by NickPiscitelli** [comment]
Yeah, `slidesToShow: auto` and fractional sliding are currently incompatible. The only way to enable fractional sliding is by providing a fractional number to the `slidesToShow` option.

> So my proposal is this: when itemWidth is set by the user, assume that user wants fractional slides.

That assumption can't be made since that breaks the main functionality of setting `slidesToShow` to `auto`, which is automatically responding to the viewport and not needing to manually set `slidesToShow` per breakpoint. Additionally, it would be impossible to know the fraction desired by the user.

In regards to reading the widths from the DOM, that is planned for future upgrades, but requires a substantial rewrite for now, not something that would be released until version two. There are a lot of complications and script bloat that come with variable widths.

It may be possible to add an additional option, `fractionalSlides`, in which the automatic `slideToShow` calculation adds the fraction specified by the new option. The `auto` argument was an after thought and was hastily added after some frustration defining multiple breakpoints for simple descending `slidesToShow` changes.

**Comment by NickPiscitelli** [comment]
This should be possible now by setting `exactWidth: true`, along with `itemWidth` and `slidesToShow: 'auto'`

**Comment by constb** [comment]
Perfect. Thanks!
